// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function handleClick(_event) {
  console.log("clicked!");
  return /* () */0;
}

function Greeter(Props) {
  var message = Props.message;
  return React.createElement("div", {
              onClick: handleClick
            }, message);
}

var make = Greeter;

var $$default = Greeter;

exports.handleClick = handleClick;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
